version: '3.7'

services:
  shifter-demo:
    build:
      context: .
    networks:
      - cssninja-services
    restart: '${MOEBIUS_DEMO_RESTART:-no}'
    labels:
      traefik.enable: true
      traefik.docker.network: 'cssninja-services'
      traefik.http.routers.shifter-demo.entrypoints: 'http'
      traefik.http.routers.shifter-demo.rule: 'Host(`shifter.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.shifter-demo.middlewares: 'https-redirect@file'
      traefik.http.services.shifter-demo-https.loadbalancer.server.port: 8080
      traefik.http.routers.shifter-demo-https.rule: 'Host(`shifter.${HOST:-127.0.0.1.nip.io}`)'
      traefik.http.routers.shifter-demo-https.tls: true
      traefik.http.routers.shifter-demo-https.entrypoints: 'https'
      traefik.http.routers.shifter-demo-https.tls.certresolver: 'http'

networks:
  cssninja-services:
    external: true
